config/routes.rb
Rails.application.routes.draw do
  resources :dishes_ingredients
  resources :ingredients
  resources :dishes do
  collection do
    get :search
    post :search
  end
end
  resources :dish_categories
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  # has_and_belongs_to_many :dishes, through: :dishes_ingredients
  has_many :dishes_ingredients

  validates :describe, presence: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:describe)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
  def ingredient_options(cur_id)
    Ingredient.all.map do |x|
      cur_id == x.id ? [x.describe + " (текущий)", x.id] : [x.describe, x.id]
    end
  end

  def new_ingredient_form(form)
    form.fields_for(:ingredient, Ingredient.new) do |ar|
      render 'dishes/ingredient_fields', ar: ar
    end
  end

  def exist_ingredient_form(form)
    form.fields_for(:ingredient) do |ar|
      render 'dishes/ingredient_fields', ar: ar
    end
  end
end

app/views/ingredients/_form.html.haml
= form_for @ingredient do |f|
  - if @ingredient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ingredient.errors.count, "error")} prohibited this ingredient from being saved:"
      %ul
        - @ingredient.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :describe
    = f.text_area :describe
  .actions
    = f.submit 'Save'

app/views/ingredients/edit.html.haml
%h1= t('app.ingredients.edit')

= render 'form'

= link_to 'Show', @ingredient
\|
= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%h1= t('app.ingredients.index')

%table.table.table-hover.table-striped.center
  %caption
    = link_to new_ingredient_path, class: 'btn btn-success' do
      = fa_icon :plus
      = t('buttons.new.ingredient')
  %thead
    %tr
      %th= Ingredient.human_attribute_name(:Describe)
      %th
      %th
      %th

  %tbody
    - @ingredients.each do |ingredient|
      %tr
        %td.center= ingredient.describe
        %td
          = link_to ingredient, class: 'btn btn-success' do
            = fa_icon :eye
        %td
          = link_to edit_ingredient_path(ingredient), class: 'btn btn-info' do
            = fa_icon :edit
        %td
          = link_to ingredient, :method => :delete, :data => { :confirm => t('helpers.sure') }, class: 'btn btn-danger' do
            = fa_icon :times
%br

= link_to 'New Ingredient', new_ingredient_path

app/views/ingredients/new.html.haml
%h1= t('app.ingredients.new')
= render 'form'

= link_to 'Back', ingredients_path

app/views/ingredients/show.html.haml
%h1= t('app.ingredients.show')

%dl
  %dt= Ingredient.human_attribute_name(:describe)
  %dd= @ingredient.describe

= link_to 'Edit', edit_ingredient_path(@ingredient)
\|
= link_to 'Back', ingredients_path