config/routes.rb
Rails.application.routes.draw do
  resources :dishes_ingredients
  resources :ingredients
  resources :dishes do
  collection do
    get :search
    post :search
  end
end
  resources :dish_categories
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/dish_category.rb
class DishCategory < ActiveRecord::Base
  belongs_to :parent, class_name: 'DishCategory', foreign_key: :dish_category_id
  has_many :dish_categories
  has_and_belongs_to_many :dishes

  validates :name, :position, presence: true
  validates :position, uniqueness: {scope: [:dish_category_id]},
    numericality: {only_integer: true, greater_than: 0}

  before_destroy :change_tree

  before_save :check_parent_self

  accepts_nested_attributes_for :dishes, allow_destroy: true

  def dish_ids=(params)
    params.split.uniq.each do |id|
      d = Dish.find_by(id: id.to_i)
      self.dishes << d if d && !(self.dishes.include?(d))
    end
  end

  private

  # перестройка дерева перед удалением
  def change_tree
    # проходим по всем детям удаляемой категории
    self.dish_categories.each do |d|
      # если есть родитель у удаляемой категории, то всех детей перевязать на неё с изменением
      # позиций детей на одном уровне
      if self.parent
        # меняем позицию ребёнка на одном уровне
        d.position = DishCategory.find_first_empty_space( self.parent.dish_categories.pluck('position') )
        d.parent = self.parent
      else
        d.position = DishCategory.find_first_empty_space( DishCategory.where(dish_category_id: nil).pluck(:position) )
        d.parent = nil
      end
      d.save
    end
  end

  # находит нужную позицию позицию, чтобы не оставалось незанятых
  # Например были позиции 1 2 3, при этом удалили 2, стало 1 3.
  # Данная функция находит ту самую вторую позицию.
  def self.find_first_empty_space(mas)
    return 1 if mas.empty?
    mas.sort!
    mas.each_with_index do |elem, index|
      return 1 if elem != index + 1 && index == 0
      if elem != index + 1
        return mas[index - 1] + 1
      elsif mas.size - 1 == index
        return mas[-1] + 1
      end
    end
  end


  def check_parent_self
    # Выбираем нужную позицию
    if parent
      # выбор позиции, среди детей родителя
      vals = parent.dish_categories.pluck("position")
      # Если детей нет у текущего родителя, то позиция первого ребёнка = 1
      self.position = DishCategory.find_first_empty_space( vals )
    else
      self.position = DishCategory.find_first_empty_space( DishCategory.where(dish_category_id: nil).pluck(:position) )
    end

    # устраняем петли
    obj1, obj2 = parent, parent
    # проверка, не сыылается ли объект сам на себя
    if obj1 == self
      return false
    else
      obj1 = obj1.try("parent")
    end

    while obj1
      # если находим один из родительских объектов, который ссылается на текущий,
      # то это петля, которую устраняем отвязыванием того элемента, который
      # ссылается на текущий одного из его же родителей
      if obj1 == self
        # Объект становится одним из корневых верших
        obj2.parent = nil
        obj2.position = DishCategory.find_first_empty_space( DishCategory.where(dish_category_id: nil).pluck(:position) )
        obj2.save
        return true
      end
      obj2 = obj1
      obj1 = obj1.parent
    end
    true
  end
end

app/controllers/dish_categories_controller.rb
class DishCategoriesController < ApplicationController
  before_action :set_dish_category, only: [:show, :edit, :update, :destroy]
  before_action -> {check_app_auth ["admin", "operator"]}

  # GET /dish_categories
  # GET /dish_categories.json
  def index
    @dish_categories = DishCategory.all
  end

  # GET /dish_categories/1
  # GET /dish_categories/1.json
  def show
  end

  # GET /dish_categories/new
  def new
    @dish_category = DishCategory.new
  end

  # GET /dish_categories/1/edit
  def edit
  end

  # POST /dish_categories
  # POST /dish_categories.json
  def create
    @dish_category = DishCategory.new(dish_category_params)

    respond_to do |format|
      if @dish_category.save
        format.html { redirect_to @dish_category, notice: 'Категория блюда создана.' }
        format.json { render :show, status: :created, location: @dish_category }
      else
        format.html { render :new }
        format.json { render json: @dish_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dish_categories/1
  # PATCH/PUT /dish_categories/1.json
  def update
    respond_to do |format|
      if @dish_category.update(dish_category_params)
        format.html { redirect_to @dish_category, notice: 'Категория блюда обновлена.' }
        format.json { render :show, status: :ok, location: @dish_category }
      else
        format.html { render :edit }
        format.json { render json: @dish_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dish_categories/1
  # DELETE /dish_categories/1.json
  def destroy
    @dish_category.destroy
    respond_to do |format|
      format.html { redirect_to dish_categories_url, notice: 'Категория блюда удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish_category
      @dish_category = DishCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_category_params
      params.require(:dish_category).permit(:name, :position, :dish_category_id, :dish_ids,
        dishes_attributes: [:id, :_destroy, :name, :instruction, :cooking_time])
    end
end

app/helpers/dish_categories_helper.rb
module DishCategoriesHelper
  # При выборе родителя в дереве категории блюд, автоматически записывается в скрытое поле позиция
  # на одном уровне с другими категориями в дереве.
  # Записывается это поле скриптом из атрибута position тега option в f.hidden_field :position
  # см. dish_categories.coffee
  def options_parent(dish_category)
    # Если не относится ни к какой, то позицию надо менять в соответствии со всеми корнями деревьев
    pos = DishCategory.find_first_empty_space( DishCategory.where(dish_category_id: nil).pluck(:position) )
    mas = [["Не относится ни к какой", "", {'position': pos}]]
    DishCategory.all.map do |d|
      next if d == dish_category
      # выбор позиции, среди детей выбранного родителя
      vals = d.dish_categories.pluck("position")
      # Если детей нет у текущего родителя, то позиция первого ребёнка = 1
      mas << [ d.name, d.id, {'position': vals.empty? ? 1 : DishCategory.find_first_empty_space( vals )} ]
    end
    mas
  end

  # def options_parent(dish_category)
  #   mas = [["Не относится ни к какой", ""]]
  #   DishCategory.all.map{|x| mas << [x.name, x.id] unless x == dish_category}
  #   mas
  # end


  def link_to_add_dish(form)
    new_object = Dish.new
    fields = form.fields_for(:dishes, new_object,
      :child_index => 'new_dish') do |fr|
      render('dish_categories/one_dish_form', fr: fr, i: 'Новое')
    end
    link_to(?#, class: 'btn btn-info',
        id: 'add_dish_link', data: {content: "#{fields}"}) do
      fa_icon("plus") + " Новое блюдо"
    end
  end

  def link_to_remove_dish(form)
    form.hidden_field(:_destroy, class: 'remove_fields') +
        link_to(?#, class: 'remove_fields remove_dish') do
      fa_icon('times', title: 'Удалить блюдо') + ' Удалить'
    end
  end
end

app/views/dish_categories/_form.html.haml
= form_for @dish_category do |f|
  = error_messages_for @dish_category
  .form-actions.bottom20
    = f.submit nil, class: 'btn btn-primary'

  = f.hidden_field :dish_ids

  .col-md-6
    .form-group
      = f.label :name
      = f.text_area :name, class: 'form-control', rows: 1
      = f.error_messages_for(:name)

  -# автоматически меняется см. dish_categories.coffee
  = f.hidden_field :position, value: 1

  .col-md-6
    .form-group
      = f.label :dish_category_id
      -# options_parent см dish_categories_helper.rb
      = f.select :dish_category_id, options_parent(@dish_category), {}, class: 'form-control'

  .col-md-12
    #exist-dishes
      %h3 Добавление существующих блюд
      .row
        .col-md-6
          = select_tag :dishes, options_from_collection_for_select(Dish.all, "id", "name"), class: 'form-control', id: "dishes-select"
        .col-md-6
          #add-exist-dish.btn.btn-info
            = fa_icon :plus
            = t('buttons.add')
          #remove-exist-dish.btn.btn-danger
            = fa_icon :times
            = t('buttons.destroy')
      .row
        .col-md-12
          #list-exist-dishes

  .row.bottom20
    .col-md-12
      -# Кнопка для добавления связи. См. dish_categories_helper.rb
      = link_to_add_dish(f)
  - i = 0
  = f.fields_for(:dishes) do |fr|
    -# Скрытое поле - id связи. Иначе все связи будут новыми
    = fr.hidden_field(:id)
    -# Чтобы не повторять код, выделяем его часть в отдельный файл
    = render('dish_categories/one_dish_form', fr: fr, i: i += 1)

app/views/dish_categories/_one_dish_form.html.haml
.col-md-6
  %div{class: 'panel panel-'+ (i.kind_of?(Integer) ? 'success' : 'info')}
    .panel-heading
      Блюдо
      = i
      %span.toright
        -# Кнопка для удаления связи. См. dish_categories_helper.rb
        = link_to_remove_dish(fr)
      .clearfix
    .panel-body
      .row
        .col-md-6
          .form-group
            = fr.label :name
            = fr.text_field :name, class: 'form-control'
            = fr.error_messages_for(:name)
        .col-md-6
          .form-group
            = fr.label :instruction
            = fr.text_area :instruction, rows: 1, class: 'form-control'
            = fr.error_messages_for(:instruction)
      .row
        .col-md-6
          .form-group
            = fr.label :cooking_time
            = fr.text_field :cooking_time, class: 'form-control'
            = fr.error_messages_for(:cooking_time)

app/views/dish_categories/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.dish_categories.edit')
  %li
    = link_to(@dish_category.name, @dish_category)
  %li
    = link_to t('headers.dish_categories.index'), dish_categories_path
  %li
    Поваренная книга

.page-header
  %h1= t('headers.dish_categories.edit')

= render 'form'

app/views/dish_categories/index.html.haml
=breadcrumb_tag do
  %li.active
    Категории блюд
  %li
    Поваренная книга

.page-header
  %h1= t('headers.dish_categories.index')
  
= link_to new_dish_category_path, class: 'btn btn-success' do
  = fa_icon :plus
  = t('buttons.new.dish_category')

.index_table
  .row
    .col-md-4.center= DishCategory.human_attribute_name(:name)
    .col-md-4.center= DishCategory.human_attribute_name(:position)
    .col-md-4.center= DishCategory.human_attribute_name(:parent)
  - @dish_categories.each do |dish_category|
    .row
      .col-md-4.center= dish_category.name
      .col-md-4.center= dish_category.position
      .col-md-4.center.bottom20= dish_category.parent ? dish_category.parent.name : "Не относится ни к какой"
      .col-md-12.center
        = link_to dish_category, class: 'btn btn-warning' do
          = fa_icon :eye
          = t('buttons.show')
        = link_to edit_dish_category_path(dish_category), class: 'btn btn-info' do
          = fa_icon :edit
          = t('buttons.edit')
        = link_to dish_category, :method => :delete,
        data: { confirm: t('buttons.confirm.dish_category') },
        class: 'btn btn-danger' do
          = fa_icon :times
          = t('buttons.destroy')

app/views/dish_categories/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.dish_categories.new')
  %li
    = link_to 'Категории блюд', dish_categories_path
  %li
    Поваренная книга

.page-header
  %h1= t('headers.dish_categories.new')

= render 'form'

app/views/dish_categories/show.html.haml
=breadcrumb_tag do
  %li.active
    = @dish_category.name
  %li
    = link_to 'Категории блюд', dish_categories_path
  %li
    Поваренная книга

%h1= @dish_category.name

%dl
  %dt= DishCategory.human_attribute_name(:name)
  %dd= @dish_category.name
  %dt= DishCategory.human_attribute_name(:position)
  %dd= @dish_category.position