config/routes.rb
Rails.application.routes.draw do
  resources :dishes_ingredients
  resources :ingredients
  resources :dishes do
  collection do
    get :search
    post :search
  end
end
  resources :dish_categories
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
    collection do
      post :create_by_admin
      get :new_by_admin
    end
  end

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  has_and_belongs_to_many :dish_categories
  # has_and_belongs_to_many :ingredients, through: :dishes_ingredients
  has_many :dishes_ingredients, dependent: :destroy

  accepts_nested_attributes_for :dishes_ingredients, allow_destroy: true

  validates :name, presence: true, uniqueness: true
  validates :instruction, presence: true
  validates :cooking_time, presence: true, numericality: {only_integer: true, greater_than: 0}

  def self.search(params)
    p1, p2, p3 = params["dish"], params["dish_category"], params["ingredient"]
    # eager_load = includes + references
    result = Dish.eager_load(:dish_categories, :dishes_ingredients, dishes_ingredients: :ingredient)
    # Поиск по полям блюд
    if p1[:name].present?
      result = result.where("dishes.name ilike ?", ?% + p1[:name] + ?%)
    end
    if p1[:instruction].present?
      result = result.where("dishes.instruction ilike ?", ?% + p1[:instruction] + ?%)
    end
    if p1[:cooking_time_from].present? && p1[:cooking_time_to].present?
      result = result.where("dishes.cooking_time BETWEEN ? AND ?",
        p1[:cooking_time_from], p1[:cooking_time_to])
    end

    # Поиск по полям категорий блюд
    if p2[:name].present?
      result = result.where("dish_categories.name ilike ?", ?% + p2[:name] + ?%)
    end

    # Поиск по полям ингредиента и связанной моделе ингредиент - блюдо
    unless p3[:disable].present?
      if p3[:name].present?
        result = result.where("ingredients.describe ilike ?", ?% + p3[:describe] + ?%)
      end
      if p3[:n_ingredients_from].present? && p3[:n_ingredients_to].present?
        result = result.where("dishes_ingredients.n_ingredients BETWEEN ? AND ?",
          p3[:n_ingredients_from], p3[:n_ingredients_to])
      end
    end

    result.all.uniq

  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  before_action -> {check_app_auth ["admin", "operator"]}

  def search
    if params["search"].present?
      @dishes = Dish.search(params["search"])
    else
      @dishes = []
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Блюдо создано.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Блюдо обновлено.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Блюдо уничтожено.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :instruction, :cooking_time, :technique,
        {dishes_ingredients_attributes: [:_destroy, :id, :dish_id, :ingredient_id, :n_ingredients,
          ingredient_attributes: [:_destroy, :id, :describe]]})
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.haml
= form_for @dish do |f|
  = error_messages_for @dish
  .form-actions.bottom20
    = f.submit nil, class: 'btn btn-primary'
  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
        = f.error_messages_for(:name)
    .col-md-6
      .form-group
        = f.label :instruction
        = f.text_area :instruction, rows: 1, class: 'form-control'
        = f.error_messages_for(:instruction)
  .row
    .col-md-6
      .form-group
        = f.label :cooking_time
        = f.text_field :cooking_time, class: 'form-control'
        = f.error_messages_for(:cooking_time)
  .row.bottom20
    .col-md-12
      -# Кнопка для добавления связи блюда-ингреденты. См. dishes_ingredients_helper
      = link_to_add_dishes_ingredients(f)
  - i = 0
  = f.fields_for(:dishes_ingredients) do |fr|
    -# Скрытое поле - id связи. Иначе все связи будут новыми
    = fr.hidden_field(:id)
    -# Чтобы не повторять код, выделяем его часть в отдельный файл
    = render('dishes/one_dishes_ingredients_form', fr: fr, i: i += 1)

app/views/dishes/_ingredient_fields.html.haml
.col-md-12
  .form-group
    = ar.label :describe
    = ar.text_field :describe, class: 'form-control'
    = ar.error_messages_for(:describe)

app/views/dishes/_one_dishes_ingredients_form.html.haml
.col-md-6
  %div{class: 'panel panel-'+ (i.kind_of?(Integer) ? 'success' : 'info')}
    .panel-heading
      Связь "блюдо - ингредиент"
      = i
      %span.toright
        -# Кнопка для удаления связи. См. role_users_helper
        = link_to_remove_dishes_ingredients(fr)
      .clearfix
    .panel-body
      .row
        .col-md-12
          .form-group
            = fr.label :n_ingredients
            = fr.text_field :n_ingredients, class: 'form-control'
            = fr.error_messages_for(:n_ingredients)
      .row
        .col-md-12
          .form-group
            = fr.label :ingredient_id
            = fr.select :ingredient_id, ingredient_options(fr.object.ingredient_id),
            {include_blank: true}, class: 'form-control ingredient-select', "data-current-id": fr.object.ingredient_id
            = fr.error_messages_for(:ingredient_id)
      .row
        %fieldset.center
          %legend Ингредиент
          %div.left.ingredient-main-fields{"data-content-new": "#{new_ingredient_form(fr)}",
            "data-content-exist": "#{exist_ingredient_form(fr)}"}
            = fr.fields_for(:ingredient) do |ar|
              = render 'dishes/ingredient_fields', ar: ar

app/views/dishes/_one_ingredient_form.html.haml
= ar.hidden_field(:id)
.col-md-12
  .form-group
    = ar.label :describe
    = ar.text_field :describe, class: 'form-control'
    = ar.error_messages_for(:describe)

app/views/dishes/_search_result.html.haml
- @dishes.each do |dish|
  .col-md-6
    %ul.list-group
      %li.list-group-item
        %span.badge= dish.name
        = Dish.human_attribute_name(:name)
      %li.list-group-item
        %span.badge= dish.instruction
        = Dish.human_attribute_name(:instruction)
      %li.list-group-item
        %span.badge= dish.cooking_time
        = Dish.human_attribute_name(:cooking_time)

app/views/dishes/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.dishes.edit')
  %li
    = link_to(@dish.name, @dish)
  %li
    = link_to t('headers.dishes.index'), dishes_path
  %li
    Поваренная книга

.page-header
  %h1= t('headers.dishes.edit')

%p.bottom20
  При выборе текущего ингредиента, его можно изменять, при выборе нового
  ингредиента, поля для него скрываются, при выборе пустоты в ингредиентах -
  можно создать новый.

= render 'form'

app/views/dishes/index.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.dishes.index')
  %li
    Поваренная книга

.page-header
  %h1= t('headers.dishes.index')


= link_to search_dishes_path, class: 'btn btn-warning' do
  = fa_icon :search
  = t('app.dishes.search')
.pull-right

= link_to new_dish_path, class: 'btn btn-success' do
  = fa_icon :plus
  = t('buttons.new.dish')

.index_table
  .row
    .col-md-4.center= Dish.human_attribute_name(:name)
    .col-md-4.center= Dish.human_attribute_name(:instruction)
    .col-md-4.center= Dish.human_attribute_name(:cooking_time)

  - @dishes.each do |dish|
    .row
      .col-md-4.center= dish.name
      .col-md-4.center= dish.instruction
      .col-md-4.center.bottom20= dish.cooking_time
      .col-md-12.center
        = link_to dish, class: 'btn btn-warning' do
          = fa_icon :eye
          = t('buttons.show')
        = link_to edit_dish_path(dish), class: 'btn btn-info' do
          = fa_icon :edit
          = t('buttons.edit')
        = link_to dish, :method => :delete,
        data: { confirm: t('buttons.confirm.dish') },
        class: 'btn btn-danger' do
          = fa_icon :times
          = t('buttons.destroy')

app/views/dishes/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.dishes.new')
  %li
    = link_to 'Блюда', dishes_path
  %li
    Поваренная книга

.page-header
  %h1= t('headers.dishes.new')

%p.bottom20
  При выборе нового ингредиента, поля для него скрываются,
  при выборе пустоты в ингредиентах - можно создать новый.

= render 'form'

app/views/dishes/search.html.haml
=breadcrumb_tag do
  %li.active
    = t('app.dishes.search')
  %li
    = link_to 'Блюда', dishes_path
  %li
    Блюда

.page-header
  %h3= t('app.dishes.search')

= form_tag search_dishes_path, method: 'get', remote: true do
  %h3 Поиск по полям блюд
  .row
    .col-md-6
      .form-group
        = label_tag Dish.human_attribute_name("name")
        = text_field_tag 'search[dish][name]', nil, class: 'form-control'
    .col-md-6
      .form-group
        = label_tag Dish.human_attribute_name("instruction")
        = text_field_tag 'search[dish][instruction]', nil, class: 'form-control'
  .row
    %fieldset
      %legend= Dish.human_attribute_name("cooking_time")
      .col-md-6
        .form-group
          = label_tag "search[dish][cooking_time_from]", t('.from')
          = number_field_tag "search[dish][cooking_time_from]", nil, class: 'form-control',
            value: Dish.pluck(:cooking_time).min
      .col-md-6
        .form-group
          = label_tag "search[dish][cooking_time_to]", t('.to')
          = number_field_tag "search[dish][cooking_time_to]", nil, class: 'form-control',
            value: Dish.pluck(:cooking_time).max
  %h3 Поиск по полям категорий
  .row
    .col-md-6
      .form-group
        = label_tag DishCategory.human_attribute_name("name")
        = text_field_tag 'search[dish_category][name]', nil, class: 'form-control'
  %h3 Поиск по полям ингредиентов
  .row
    .col-md-12
      .form-group
        = check_box_tag "search[ingredient][disable]"
        = label_tag "search[ingredient][disable]", t(".disable_ingredients")
  .row
    %fieldset
      %legend= DishesIngredient.human_attribute_name("n_ingredients")
      .col-md-6
        .form-group
          = label_tag "search[ingredient][n_ingredients_from]", t('.from')
          = number_field_tag "search[ingredient][n_ingredients_from]", nil, class: 'form-control',
            value: DishesIngredient.pluck(:n_ingredients).min
      .col-md-6
        .form-group
          = label_tag "search[ingredient][n_ingredients_to]", t('.to')
          = number_field_tag "search[ingredient][n_ingredients_to]", nil, class: 'form-control',
            value: DishesIngredient.pluck(:n_ingredients).max
  .row
    .col-md-6
      .form-group
        = label_tag Ingredient.human_attribute_name("describe")
        = text_field_tag 'search[ingredient][describe]', nil, class: 'form-control'

  .form-actions.bottom20
    = submit_tag nil, class: 'btn btn-primary'

#insert_found_dishes
  %p Не найдено

app/views/dishes/search.js.erb
<% if @dishes.present? %>
  $("#insert_found_dishes").html("<%= j render 'search_result' %> ")
<% else %>
  $("#insert_found_dishes").html("<p>Не найдено</p>")
<% end %>

app/views/dishes/show.html.haml
=breadcrumb_tag do
  %li.active
    = @dish.name
  %li
    = link_to 'Блюда', dishes_path
  %li
    Поваренная книга

%h1= @dish.name

%dl
  %dt= Dish.human_attribute_name(:name)
  %dd= @dish.name
  %dt= Dish.human_attribute_name(:instruction)
  %dd= @dish.instruction
  %dt= Dish.human_attribute_name(:cooking_time)
  %dd= @dish.cooking_time

= link_to @dish, class: 'btn btn-warning' do
  = fa_icon :eye
  = t('buttons.show')
= link_to edit_dish_path(@dish), class: 'btn btn-info' do
  = fa_icon :edit
  = t('buttons.edit')
= link_to @dish, :method => :delete,
data: { confirm: t('buttons.confirm.dish') },
class: 'btn btn-danger' do
  = fa_icon :times
  = t('buttons.destroy')